export const CPTALabelConfig = [
  {
    uniqId: "wcf-cpt-label-menu-name",
    label: "Menu Name",
    key: "menu_name",
    placeholder: "Enter Text",
    description: "Admin menu name for the post type.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-all-items",
    label: "All Items",
    key: "all_items",
    placeholder: "Enter Text",
    description: "In the post type submenu in the admin dashboard.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-edit-item",
    label: "Edit Item",
    key: "edit_item",
    placeholder: "Enter Text",
    description: "At the top of the editor screen when editing an item.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-view-item",
    label: "View Item",
    key: "view_item",
    placeholder: "Enter Text",
    description: "In the admin bar to view item when editing it.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-view-items",
    label: "View Items",
    key: "view_items",
    placeholder: "Enter Text",
    description:
      "Appears in the admin bar in the 'All Posts' view, provided the post type supports archives and the home page is not an archive of that post type.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-add-new-items",
    label: "Add New Item",
    key: "add_new_item",
    placeholder: "Enter Text",
    description: "At the top of the editor screen when adding a new item.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-add-new",
    label: "Add New",
    key: "add_new",
    placeholder: "Enter Text",
    description: "In the post type submenu in the admin dashboard.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-new-item",
    label: "New Item",
    key: "new_item",
    placeholder: "Enter Text",
    description: "In the post type submenu in the admin dashboard.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-parent-item-prefix",
    label: "Parent Item Prefix",
    key: "parent_item_colon",
    placeholder: "Enter Text",
    description: "For hierarchical types in the post type list screen.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-search-items",
    label: "Search Items",
    key: "search_items",
    placeholder: "Enter Text",
    description: "At the top of the items screen when searching for an item.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-no-items-found",
    label: "No Items Found",
    key: "not_found",
    placeholder: "Enter Text",
    description:
      "At the top of the post type list screen when there are no posts to display.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-no-items-found-trash",
    label: "No Items Found in Trash",
    key: "not_found_in_trash",
    placeholder: "Enter Text",
    description:
      "At the top of the post type list screen when there are no posts in the trash.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-archives-nav-menu",
    label: "Archives Nav Menu",
    key: "archives",
    placeholder: "Enter Text",
    description:
      "At the top of the post type list screen when there are no posts in the trash.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-attributes-meta-box",
    label: "Attributes Meta Box",
    key: "attributes",
    placeholder: "Enter Text",
    description:
      "In the editor used for the title of the post attributes meta box.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-featured-image-meta-box",
    label: "Featured Image Meta Box",
    key: "featured_image",
    placeholder: "Enter Text",
    description:
      "In the editor used for the title of the featured image meta box.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-set-featured-image",
    label: "Set Featured Image",
    key: "set_featured_image",
    placeholder: "Enter Text",
    description: "As the button label when setting the featured image.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-remove-featured-image",
    label: "Remove Featured Image",
    key: "remove_featured_image",
    placeholder: "Enter Text",
    description: "As the button label when removing the featured image.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-use-featured-image",
    label: "Use Featured Image",
    key: "use_featured_image",
    placeholder: "Enter Text",
    description: "As the button label when removing the featured image.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-insert-into-media-button",
    label: "Insert Into Media Button",
    key: "insert_into_item",
    placeholder: "Enter Text",
    description: "As the button label when adding media to content.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-uploaded-to-this-item",
    label: "Uploaded To This Item",
    key: "uploaded_to_this_item",
    placeholder: "Enter Text",
    description: "In the media modal showing all media uploaded to this item.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-filter-items-list",
    label: "Filter Items List",
    key: "filter_items_list",
    placeholder: "Enter Text",
    description:
      "Used by screen readers for the filter links heading on the post type list screen.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-filter-items-by-date",
    label: "Filter Items By Date",
    key: "filter_by_date",
    placeholder: "Enter Text",
    description:
      "Used by screen readers for the filter by date heading on the post type list screen.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-items-list-navigation",
    label: "Items List Navigation",
    key: "items_list_navigation",
    placeholder: "Enter Text",
    description:
      "Used by screen readers for the filter by date heading on the post type list screen.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-items-list",
    label: "Items List",
    key: "items_list",
    placeholder: "Enter Text",
    description:
      "Used by screen readers for the items list on the post type list screen.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-item-published",
    label: "Item Published",
    key: "item_published",
    placeholder: "Enter Text",
    description: "In the editor notice after publishing an item.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-item-published-privately",
    label: "Item Published Privately",
    key: "item_published_privately",
    placeholder: "Enter Text",
    description: "In the editor notice after publishing a private item.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-item-reverted-to-draft",
    label: "Item Reverted To Draft",
    key: "item_reverted_to_draft",
    placeholder: "Enter Text",
    description: "In the editor notice after reverting an item to draft.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-item-scheduled",
    label: "Item Scheduled",
    key: "item_scheduled",
    placeholder: "Enter Text",
    description: "In the editor notice after scheduling an item.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-item-updated",
    label: "Item Updated",
    key: "item_updated",
    placeholder: "Enter Text",
    description: "In the editor notice after an item is updated.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-item-link",
    label: "Item Link",
    key: "item_link",
    placeholder: "Enter Text",
    description: "Title for a navigation link block variation.",
    value: "",
  },
  {
    uniqId: "wcf-cpt-label-item-link-description",
    label: "Item Link Description",
    key: "item_link_description",
    placeholder: "Enter Text",
    description: "Description for a navigation link block variation.",
    value: "",
  },
];
