export const CTALabelConfig = [
  {
    uniqId: "wcf-ct-label-menu-label",
    label: "Menu Label",
    key: "name",
    placeholder: "Enter Text",
    description: "Assigns the menu name text.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-all-items",
    label: "All Items",
    key: "all_items",
    placeholder: "Enter Text",
    description: "In the post type submenu in the admin dashboard.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-edit-item",
    label: "Edit Item",
    key: "edit_item",
    placeholder: "Enter Text",
    description: "At the top of the editor screen when editing an item.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-view-item",
    label: "View Item",
    key: "view_item",
    placeholder: "Enter Text",
    description: "In the admin bar to view item when editing it.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-update-items",
    label: "Update Item",
    key: "update_item",
    placeholder: "Enter Text",
    description: "Assigns the update item text.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-add-new-items",
    label: "Add New Item",
    key: "add_new_item",
    placeholder: "Enter Text",
    description: "At the top of the editor screen when adding a new item.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-add-new",
    label: "New Item Name",
    key: "new_item_name",
    placeholder: "Enter Text",
    description: "Assigns the new item name text.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-search-items",
    label: "Search Items",
    key: "search_items",
    placeholder: "Enter Text",
    description: "Assigns search items text.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-popular-tems",
    label: "Popular Items",
    key: "popular_items",
    placeholder: "Enter Text",
    description:
      "Assigns popular items text. Only used for non-hierarchical taxonomies.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-separate-items-with-commas",
    label: "Separate Items With Commas",
    key: "separate_items_with_commas",
    placeholder: "Enter Text",
    description:
      "Assigns the separate item with commas text used in the taxonomy meta box. Only used on non-hierarchical taxonomies.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-add-or-remove-items",
    label: "Add Or Remove Items",
    key: "add_or_remove_items",
    placeholder: "Enter Text",
    description:
      "Assigns the add or remove items text used in the meta box when JavaScript is disabled. Only used on non-hierarchical taxonomies",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-choose-from-most-used",
    label: "Choose From Most Used",
    key: "choose_from_most_used",
    placeholder: "Enter Text",
    description:
      "Assigns the 'choose from most used' text used in the meta box when JavaScript is disabled. Only used on non-hierarchical taxonomies.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-most-used",
    label: "Most Used",
    key: "most_used",
    placeholder: "Enter Text",
    description: "Assigns text to the Title field of the Most Used tab.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-not-found",
    label: "Not Found",
    key: "not_found",
    placeholder: "Enter Text",
    description:
      "Assigns the text displayed when clicking the 'choose from most used' text in the taxonomy meta box when no tags are available, and assigns the text used in the terms list table when there are no items for a taxonomy.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-no-terms",
    label: "No Terms",
    key: "no_terms",
    placeholder: "Enter Text",
    description:
      "Assigns the text displayed in the posts and media list tables when no tags or categories are available.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-name-field-description",
    label: "Name Field Description",
    key: "name_field_description",
    placeholder: "Enter Text",
    description: "Describes the Name field on the Edit Tags screen.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-slug-field-description",
    label: "Slug Field Description",
    key: "slug_field_description",
    placeholder: "Enter Text",
    description: "Describes the Slug field on the Edit Tags screen.",
    value: "",
    iType: "textarea",
  },
  {
    uniqId: "wcf-ct-label-description-field-description",
    label: "Description Field Description",
    key: "desc_field_description",
    placeholder: "Enter Text",
    description: "Describes the Description field on the Edit Tags screen.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-items-list-navigation",
    label: "Items List Navigation",
    key: "items_list_navigation",
    placeholder: "Enter Text",
    description: "Assigns text to the table pagination hidden heading.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-items-list",
    label: "Items List",
    key: "items_list",
    placeholder: "Enter Text",
    description: "Assigns text to the table hidden heading.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-back-to-items",
    label: "Back To Items",
    key: "back_to_items",
    placeholder: "Enter Text",
    description:
      "Assigns the text used to link back to the main index after updating a term.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-item-link",
    label: "Item Link",
    key: "item_link",
    placeholder: "Enter Text",
    description:
      "Assigns a title for navigation link block variation used in the block editor.",
    value: "",
  },
  {
    uniqId: "wcf-ct-label-item-link-description",
    label: "Item Link Description",
    key: "item_link_description",
    placeholder: "Enter Text",
    description:
      "Describes a navigation link block variation used in the block editor.",
    value: "",
  },
];
