export const PostTypeConfig = {
  plural_label: "",
  singular_label: "",
  post_type_key: "",
  public: false,
  hierarchical: false,
  advance_config: false,
  advance_settings: [
    {
      name: "General",
      tab_key: "general",
      supports: [],
      description: "",
      active: false,
    },
    {
      name: "Visibility",
      tab_key: "visibility",
      show_in_ui: false,
      show_in_admin_menu: false,
      admin_menu_parent: "",
      menu_position: "",
      menu_icon: "",
      custom_metabox_callback: "",
      show_in_admin_bar: false,
      appearance_menus_support: false,
      exclude_from_search: false,
    },
    {
      name: "URLs",
      tab_key: "urls",
      permalink_rewrite: "",
      url_slug: "",
      front_url_prefix: false,
      feed_url: false,
      pagination: false,
      archive: false,
      publicly_queryable: false,
      query_variable_support: "",
    },
    {
      name: "Permissions",
      tab_key: "permissions",
      rename_capabilities: false,
      can_export: false,
      delete_with_user: false,
    },
  ],
};
