<?php
/**
 *
 * @package WCFOI
 */

namespace WCFOI;

class ReduxImporter {
	/**
	 * Import Redux data from a JSON file, generated by the Redux plugin.
	 *
	 * @param array $import_data Array of arrays. Child array contains 'option_name' and 'file_path'.
	 */
	public static function import( $import_data ) {
		$wcfio          = OneClickDemoImport::get_instance();
		$log_file_path = $wcfio->get_log_file_path();	
	}
}
